# Generated by Django 5.2.12 on 2026-04-06 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_identificador', models.CharField(help_text='Ej: prompt_softcomputing_v1', max_length=100, unique=True)),
                ('system_instruction', models.TextField(help_text='Rol y contexto general para Gemini.')),
                ('prompt_body', models.TextField(help_text='El esqueleto del prompt con variables. Ej: {calificaciones}')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"ia"."prompt_template"',
            },
        ),
        migrations.CreateModel(
            name='RegistroAnalisisIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_entrada_json', models.JSONField(help_text='JSON exacto que se recibió del Frontend')),
                ('respuesta_ia_json', models.JSONField(help_text='JSON estructurado que devolvió Gemini')),
                ('exitoso', models.BooleanField(default=True, help_text='Indica si la IA respondió sin errores')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prompt_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiubetesis.prompttemplate')),
            ],
            options={
                'db_table': '"ia"."registro_analisis_ia"',
            },
        ),
    ]
