# Generated by Django 5.2.13 on 2026-04-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiubetesis', '0003_datos_genericos_isi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroanalisisia',
            name='respuesta_ia_json',
            field=models.JSONField(blank=True, help_text='JSON estructurado que devolvió Gemini', null=True),
        ),
        migrations.CreateModel(
            name='SolucionGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera_nombre', models.CharField(max_length=150)),
                ('asignatura_codigo', models.CharField(max_length=20)),
                ('asignatura_nombre', models.CharField(max_length=150)),
                ('paralelo_id', models.IntegerField(blank=True, null=True)),
                ('docente_nombre', models.CharField(max_length=150)),
                ('docente_id', models.CharField(blank=True, max_length=50)),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('cantidad_estudiantes_recuperacion', models.IntegerField(default=0)),
                ('diagnostico_json', models.JSONField(help_text='JSON estructurado DiagnosticoIADTO devuelto por Gemini')),
                ('exitoso', models.BooleanField(default=True)),
                ('periodo_codigo', models.CharField(default='', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registro_analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soluciones', to='aiubetesis.registroanalisisia')),
            ],
            options={
                'db_table': '"ia"."solucion_generada"',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['periodo_codigo', 'asignatura_codigo'], name='solucion_ge_periodo_094034_idx'), models.Index(fields=['exitoso', 'fecha_creacion'], name='solucion_ge_exitoso_1ff276_idx')],
            },
        ),
    ]
